function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end
Citizen.CreateThread(function()
    AddTextEntry('800pro', 'Polaris 800 PRO RMK')
    AddTextEntry('m235', 'BMW M2')
    AddTextEntry('silveradoprerunner', 'Silverado PreRunner')
    AddTextEntry('widebodyled', '21 Dodge Charger Hellcat')
    AddTextEntry('nismo20', '20 Godzilla Nismo GTR')
    AddTextEntry('btsupra94', '94 Supra')
    AddTextEntry('gtz34', 'Drift GTR SE')
    AddTextEntry('lb750sv', 'Lamborghini 750')
    AddTextEntry('rm3e36', 'BMW Rmod E-38')
    AddTextEntry('promod2', 'Promod Truck')
    AddTextEntry('65c10', '1965 C-10')
    AddTextEntry('EK9', 'Honda EK9')
    AddTextEntry('dc5', 'Honda DC5')
    AddTextEntry('lc500', 'Liberty Walk Lexus lc500')
    AddTextEntry('m4c20', 'RedEye BMW')
    AddTextEntry('emsa', 'Ambulance Rig')
    AddTextEntry('emsc', 'EMS Charger')
    AddTextEntry('emsf', 'EMS F350')
    AddTextEntry('emst', 'EMS Tahoe')
    AddTextEntry('19gt500', 'Mustang Cobra')
    AddTextEntry('valor', 'Police 2018 Charger')
    AddTextEntry('valor2', 'Police Crown Vic')
    AddTextEntry('valor3', 'Police FPIS')
    AddTextEntry('valor4', 'Police 2008 Charger')
    AddTextEntry('valor5', 'Police Tahoe')
    AddTextEntry('valor6', 'Police Marked F150')
    AddTextEntry('models', 'Tesla Model S')
    AddTextEntry('valor7', 'Police 2015 FPIU')
    AddTextEntry('code3mustang', 'Police Mustang')
    AddTextEntry('fastback', 'Police UC Fastback Mustang')
    AddTextEntry('code3durango', 'Police Durango')
    AddTextEntry('majfd', 'Mazda RX-FD')
    AddTextEntry('pluto335', 'BMW 335i')
    AddTextEntry('ctsv16', 'Cadillac CTSv')
    AddTextEntry('gle21', 'Mercedes GLE')
    AddTextEntry('lp700r', 'Lamborghini Aventador LP-700R')
    AddTextEntry('rmodcamaro', 'R-Mod Camaro')
    AddTextEntry('720s', '2017 McLaren 720s')
    AddTextEntry('ram', 'Police Ram')
    AddTextEntry('f150', 'Police F150')
    AddTextEntry('durango', 'Durango')
    AddTextEntry('bmwbike', 'BMW Motorcycle')
    AddTextEntry('20ram2500', 'Dodge Ram 2500')
    AddTextEntry('fdsuv', 'EMS Unmarked Jeep')
    AddTextEntry('pd_tesla', 'EMS Unmarked Tesla')
    AddTextEntry('gsxr19', '2019 GSX-R')
    AddTextEntry('2f2fgtr34', 'Custom R34 Skyline')
    AddTextEntry('eleanor', 'GT500 Eleanor')
    AddTextEntry('mvisiongt', 'Mercedes-Benz AMG Vision GT')
    AddTextEntry('vicechee', 'Vice Detective Car')
    AddTextEntry('16challenger', '2016 Hemi Challenger')
    AddTextEntry('16charger', 'Red Eye 2016 Charger')
    AddTextEntry('16m5', 'Crossover M5')
    AddTextEntry('17m760i', 'BMW 760i')
    AddTextEntry('2020CLA45s', 'Mercedes CLA 45s')
    AddTextEntry('420x', 'Nissian 240 Race')
    AddTextEntry('4c', 'Alfa Romeo 4c')
    AddTextEntry('84rx7k', '1984 RX-7')
    AddTextEntry('a80', 'Toyota Supra')
    AddTextEntry('amdbx', 'Aston Martin DBX')
    AddTextEntry('amggtrr20', 'Mercedes AMG GTR')
    AddTextEntry('ap2', 'Honda S2000')
    AddTextEntry('audquattros', 'Audi Quattro')
    AddTextEntry('ayxz', 'Rolls Royce Ghost')
    AddTextEntry('bc91sir', '1991 Honda CRX')
    AddTextEntry('c63wb', 'Mercedes c63s')
    AddTextEntry('c7', 'Corvette C7')
    AddTextEntry('camrs17', '2017 Camaro')
    AddTextEntry('cesc21', 'Cadillac Escalade')
    AddTextEntry('cgt', 'Carrera GT')
    AddTextEntry('ctsv16', 'CTS-V')
    AddTextEntry('dc2', 'Honda Dc2')
    AddTextEntry('demon', '2018 Demon Challenger')
    AddTextEntry('demonhawk', 'Jeep Demonhawk')
    AddTextEntry('e36gda', 'BMW e36')
    AddTextEntry('e400', 'Mercedes e400')
    AddTextEntry('e53', 'BMW X-5')
    AddTextEntry('ericdailyg8', 'Pontiac G8')
    AddTextEntry('fk8', 'Honda Civic Type-R Hatch')
    AddTextEntry('fleet78low', '78 Cadiliac')
    AddTextEntry('G65', 'Mercedes G65')
    AddTextEntry('gdaq50', 'Infiniti G37')
    AddTextEntry('GODzDEMONLB', '2018 Hellcat Challenger')
    AddTextEntry('GODzS2kPNDMCR', 'Custom Honda S2000')
    AddTextEntry('honcrx91', '91 Honda CRX')
    AddTextEntry('impala', '98 Impala')
    AddTextEntry('m3f80', 'BMW M3')
    AddTextEntry('m3kean', 'BMW M3 V2')
    AddTextEntry('Mustang', '5.0 Mustang ')
    AddTextEntry('mxpan', 'Mazda MX-5')
    AddTextEntry('nissantitan17', 'Nissan Titan')
    AddTextEntry('nzp', 'Nismo 370z')
    AddTextEntry('onyxaventador', 'Lamborghini Aventador')
    AddTextEntry('p1', 'Mclaren P1')
    AddTextEntry('phantom8', 'Rolls Royce Phantom')
    AddTextEntry('pkr1', 'Yamaha R1')
    AddTextEntry('pluto15silvt', '2015 Slammed Silverado')
    AddTextEntry('r8ppi', 'Audi R8')
    AddTextEntry('rculi', 'Rolls Royce Cullinan')
    AddTextEntry('rmod240sx', 'R-Mod 240sx')
    AddTextEntry('rmodgtr50', 'Nismo GTR')
    AddTextEntry('rmodm5e34', 'BMW M5')
    AddTextEntry('rmodz350pandem', 'Nissian 350zNISMO')
    AddTextEntry('RollsRoyceCP', 'Rolls Royce')
    AddTextEntry('RS72020', 'Audi RS7')
    AddTextEntry('scubieblob', 'Subaru WRX')
    AddTextEntry('sil80', 'Silmod 240sx')
    AddTextEntry('sl500', 'Mercedes sl500')
    AddTextEntry('subwrx', '06 Subaru WRX')
    AddTextEntry('v250', 'Mercedes v250')
    AddTextEntry('viper', 'Dodge Viper')
    AddTextEntry('z4', 'BMW Z4')
    AddTextEntry('zx10r', 'Ninja ZX-10R')
    AddTextEntry('17r35', '2017 GT-R35')
    AddTextEntry('2020Copo', '2020 Race Camaro')
    AddTextEntry('2020silv', '2020 Silverado')
    AddTextEntry('aperta', 'La Ferreri Aperta')
    AddTextEntry('bbentayga', 'Bently Bentayga')
    AddTextEntry('cosworth', 'Cosworth')
    AddTextEntry('fnfrx7', 'Wide Body RX-7')
    AddTextEntry('forgieC7', 'Forgie Corvette c7')
    AddTextEntry('GODzPANDEMC8', 'Corvette C8')
    AddTextEntry('granlb', 'Maserati Liberty Walk')
    AddTextEntry('megaramcustom', '2010 Dodge Ram 2500 Megaram Custom')
    AddTextEntry('gsnake', 'Super Snake')
    AddTextEntry('nc1', 'Acura NSX')
    AddTextEntry('pd458wb', 'Ferrari 458 Widebody')
    AddTextEntry('r1', 'Custom Yamaha R1')
    AddTextEntry('rtrdxr', 'Drift RTR')
    AddTextEntry('streetsupra', 'Street Supra')
    AddTextEntry('subaru', 'Suburu WRX')
    AddTextEntry('sultanrsv8', 'Sultan-RS V8')
    AddTextEntry('teslax', 'Tesla Model X')
    AddTextEntry('trailcat', 'Jeep Trailcat')
    AddTextEntry('00f350d', 'Ford F350 Dually')
    AddTextEntry('10ram', '2010  Ram')
    AddTextEntry('15tahoe', 'Chevy Tahoe')
    AddTextEntry('bc052500', 'GMC Sierra')
    AddTextEntry('bc20hauler', 'Gooseneck Hauler')
    AddTextEntry('camperman', 'ToyHauler')
    AddTextEntry('chauler', '10ft Trailer')
    AddTextEntry('forgiato2500', 'Ram2500 Super Duty')
    AddTextEntry('20fttrailer', '20ft Trailer')
    AddTextEntry('cotrailer', '25ft Trailer')
    AddTextEntry('ctrailer', 'Enclosed TrailerV2')
    AddTextEntry('enclosedgoose', 'Enclosed Trailer')
    AddTextEntry('trailercar', '18ft Trailer')
    AddTextEntry('fatboy', 'Harley Davidson Fatboy')
    AddTextEntry('flhxs_streetglide_special18', 'Harley Davidson Street Glide')
    AddTextEntry('HDIron883', 'Harley Davidson Iron883')
    AddTextEntry('na25', 'Harley Davidson Road King')
    AddTextEntry('gt86trust', 'Toyota Gt86 Trust')
    AddTextEntry('evoz', 'Mitsubishi Lancer')
    AddTextEntry('q709', 'Audi Q7 2009')
    AddTextEntry('a8lw12', 'Audi A8 2012')
end)